FROM ubuntu
RUN touch file1 file2 aws
HELLO THIS IS EXTRA DATA WE ARE ADDING TO THIS FILE
ADDING SOME MORE CONTENTw
THIS IS JENKINS CLASS, THANKS FOR JOININ
475683973023@#$%^&*()
ADDING SOME NEW CONTENT BY DEV-4
